import { ComponentProps } from "@motionly/base";

export const props: ComponentProps[] = [
  {
    comp: "text",
    textStyle: {
      color: {
        type: "basic",
        color: "#000000FF",
      },
      fontSize: 120,
      fontFamily: "Inter",
      fontWeight: 700,
      textAlign: "left",
    },
    text: `const idk ={\n  tere: "{{green}}{{blue}}{{yellow}}"\n}`,
    justifyContent: "start",
    id: "rj32x9",
    x: 0,
    y: 0,
    width: 1080,
    height: 1080,
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [
      {
        prop: "text",
        type: "spring",
        start: 1,
        from: 1,
        to: 0,
        duration: 1,
        mass: 1,
        damping: 14,
        stiffness: 80,
        variable: "green",
        value: "green",
      },
      {
        prop: "text",
        type: "spring",
        start: 2,
        from: 0,
        to: 1,
        duration: 1,
        mass: 1,
        damping: 14,
        stiffness: 80,
        variable: "blue",
        value: "blue",
      },
      {
        prop: "text",
        type: "spring",
        start: 3,
        from: 0,
        to: -1,
        duration: 1,
        mass: 1,
        damping: 14,
        stiffness: 80,
        variable: "blue",
      },
      {
        prop: "text",
        type: "spring",
        start: 4,
        from: 0,
        to: 1,
        duration: 1,
        mass: 1,
        damping: 14,
        stiffness: 80,
        variable: "yellow",
        value: "yellow",
      },
    ],
  },
  {
    comp: "div",
    bg: {
      type: "interpolate",
      colors: [
        {
          color: "#11ff00ff",
          start: 1,
        },
        {
          color: "#11ff00ff",
          start: 2.9,
        },
        {
          color: "#004cffff",
          start: 3,
        },
        {
          color: "#004cffff",
          start: 4.9,
        },
        {
          color: "#fff700ff",
          start: 5,
        },
      ],
    },
    comps: [],
    id: "ylubldy",
    x: 390.59722429999954,
    y: 447.3888961999998,
    width: 500,
    height: 500,
    borderRadius: 20,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
  {
    comp: "text",
    textStyle: {
      color: {
        type: "basic",
        color: "#000000FF",
      },
      fontSize: 120,
      fontFamily: "Inter",
      fontWeight: 700,
      textAlign: "center",
    },
    text: "{{time}}",
    justifyContent: "center",
    id: "jtmyoxk",
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [
      {
        prop: "number",
        type: "interpolate",
        start: 0,
        from: 0,
        to: 10,
        duration: 0,
        variable: "time",
      },
    ],
    x: 406.4567014999999,
    y: 424.3820247,
  },
  {
    comp: "div",
    bg: {
      type: "interpolate",
      colors: [
        {
          color: "#11ff00ff",
          start: 1,
        },
        {
          color: "#004cffff",
          start: 1.1,
        },
        {
          color: "#004cffff",
          start: 3,
        },
        {
          color: "#fff700ff",
          start: 3.1,
        },
      ],
    },
    comps: [],
    id: "iswt2x",
    x: 444.73401239999953,
    y: 387.80397499999975,
    width: 500,
    height: 500,
    borderRadius: 20,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
];
