import Head from "next/head";
import { Inter } from "@next/font/google";
import { Player } from "@asius/player";
import { props } from "../props";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [text, setText] = useState("Your text");
  const [seed, setSeed] = useState("sdf");
  const [color, setColor] = useState("#FFFFFF");
  const modifications = [
    {
      id: "q4amc47",
      text,
    },
    {
      id: "ekmz32",
      src: `https://picsum.photos/seed/${seed}/500/500`,
    },
    {
      id: "1obb3k",
      textStyle: {
        fontSize: 200,
        fontFamily: "Arial",
        color: color,
        outline: {
          color: "#ff0000",
          width: 14,
        },
        fontWeight: 800,
        lineHeight: 1.2,
        textAlign: "center",
      },
    },
  ];
  return (
    <>
      <Head>
        <title>Asius example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ maxWidth: "600px", margin: "auto" }}>
          <input
            type="text"
            placeholder="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <input
            type="text"
            placeholder="image seed"
            value={seed}
            onChange={(e) => setSeed(e.target.value)}
          />
          <input
            type="color"
            placeholder="color"
            value={color}
            onChange={(e) => setColor(e.target.value)}
          />
          <Player
            comps={props}
            duration={40}
            fps={30}
            height={1080}
            width={1080}
            style={{ width: `100%` }}
            controls
            modifications={modifications}
          />
        </div>
      </main>
    </>
  );
}
