import Head from "next/head";
import { Player } from "@motionly/player";
import { props } from "../props";
import { useState } from "react";
import { useRender } from "@motionly/renderer/dist/sdk";

const template = {
  height: 1080,
  width: 1080,
  fps: 30,
  duration: 40,
  comps: props,
};

export default function Home() {
  const [text, setText] = useState("Your text");
  const [seed, setSeed] = useState("sdf");
  const [color, setColor] = useState("#FFFFFF");

  const modifications = [
    {
      id: "m5sk14y",
      text,
    },
    {
      id: "r81ebs",
      src: `https://picsum.photos/seed/${seed}/1080/1080`,
    },
    {
      id: "skz7v8m",
      color,
    },
  ];

  const { media, status, progress, fileUrl } = useRender({
    ...template,
    frame: 0,
  });

  return (
    <>
      <Head>
        <title>Motionly example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ maxWidth: "600px", margin: "auto" }}>
          <input
            type="text"
            placeholder="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <input
            type="text"
            placeholder="image seed"
            value={seed}
            onChange={(e) => setSeed(e.target.value)}
          />
          <input
            type="color"
            placeholder="color"
            value={color}
            onChange={(e) => setColor(e.target.value)}
          />
          <Player
            comps={props}
            duration={40}
            fps={30}
            height={1080}
            width={1080}
            style={{ width: `100%` }}
            controls
          />
          {status ? (
            <div>
              <p>Rendering...</p>
              <p>{status}</p>
              <p>{progress}%</p>
              <p>{fileUrl}</p>
            </div>
          ) : (
            <button onClick={media}>Render</button>
          )}
        </div>
      </main>
    </>
  );
}
